// ============================================================
// app/api/unlock-requests/route.ts
// POST /api/unlock-requests  — submit an unlock request
// ============================================================
// SECURITY RULES:
//   - approvalToken is NEVER returned to the requesting user
//   - approvalToken is generated server-side via Prisma default
//   - Cooldown is enforced server-side — client cannot bypass it
//   - Box must be LOCKED status to submit a request
//   - Only one PENDING request allowed per box at a time
// ============================================================

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { BOX_STATUS, UNLOCK_STATUS } from "@/lib/types";
import { sendUnlockRequestToKeyholder } from "@/lib/email";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { boxId, reason, reflection } = body;

    if (!boxId || !reason) {
      return NextResponse.json(
        { error: "boxId and reason are required" },
        { status: 400 }
      );
    }

    // Verify box exists and belongs to this user
    const box = await prisma.box.findUnique({
      where: { id: boxId },
      include: {
        keyholder: true,
        unlockRequests: {
          where: { status: UNLOCK_STATUS.PENDING },
          orderBy: { requestedAt: "desc" },
          take: 1,
        },
      },
    });

    if (!box) {
      return NextResponse.json({ error: "Box not found" }, { status: 404 });
    }

    if (box.userId !== session.user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // Box must be locked to submit an unlock request
    if (box.status !== BOX_STATUS.LOCKED) {
      return NextResponse.json({ error: "Box is not locked" }, { status: 400 });
    }

    // Only one pending request allowed at a time
    if (box.unlockRequests.length > 0) {
      return NextResponse.json(
        { error: "A pending unlock request already exists for this box" },
        { status: 409 }
      );
    }

    // Enforce cooldown server-side — cannot be bypassed by the client
    const lastRequest = await prisma.unlockRequest.findFirst({
      where: { boxId },
      orderBy: { requestedAt: "desc" },
    });

    if (lastRequest?.cooldownUntil && lastRequest.cooldownUntil > new Date()) {
      const minutesLeft = Math.ceil(
        (lastRequest.cooldownUntil.getTime() - Date.now()) / 1000 / 60
      );
      return NextResponse.json(
        {
          error: `Cooldown active. Try again in ${minutesLeft} minute(s).`,
          cooldownUntil: lastRequest.cooldownUntil,
        },
        { status: 429 }
      );
    }

    // Create the unlock request
    // approvalToken is auto-generated by Prisma — never touches the client
    const unlockRequest = await prisma.unlockRequest.create({
      data: {
        boxId,
        reason: reason.trim(),
        reflection: reflection ? reflection.trim() : null,
        status: UNLOCK_STATUS.PENDING,
        // Set a 24-hour cooldown on the next request if this one is denied
        cooldownUntil: null,
      },
    });

    // Update box status to UNLOCK_PENDING
    await prisma.box.update({
      where: { id: boxId },
      data: { status: BOX_STATUS.UNLOCK_PENDING },
    });

    // Notify keyholder via email if one exists
    if (box.keyholder?.accepted && box.keyholder.email) {
      await sendUnlockRequestToKeyholder({
        keyholderEmail: box.keyholder.email,
        keyholderName: box.keyholder.name,
        ownerName: session.user.name,
        boxName: box.name,
        reason,
        reflection,
        approvalToken: unlockRequest.approvalToken,
      });
    }
    // The keyholder email should contain:
    //   - The user's reason and reflection
    //   - An APPROVE link: /api/unlock-requests/[token]/approve
    //   - A DENY link:    /api/unlock-requests/[token]/deny
    // The approvalToken is: unlockRequest.approvalToken
    // NEVER send the approvalToken to the box owner under any circumstance

    // Return the request WITHOUT the approvalToken
    const { approvalToken: _, ...safeRequest } = unlockRequest;

    return NextResponse.json(safeRequest, { status: 201 });
  } catch (error) {
    console.error("[POST /api/unlock-requests]", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
