// ============================================================
// app/api/keyholders/route.ts
// POST /api/keyholders  — invite a keyholder to a box
// ============================================================
// SECURITY RULES:
//   - Only the box owner can invite a keyholder
//   - A box can only have one keyholder
//   - inviteToken is generated server-side and sent via email only
//   - The token is never returned in the API response
// ============================================================

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { sendKeyholderInvite } from "@/lib/email";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { boxId, email, name } = body;

    if (!boxId || !email) {
      return NextResponse.json(
        { error: "boxId and email are required" },
        { status: 400 }
      );
    }

    // Verify the box exists and belongs to this user
    const box = await prisma.box.findUnique({
      where: { id: boxId },
      include: { keyholder: true },
    });

    if (!box) {
      return NextResponse.json({ error: "Box not found" }, { status: 404 });
    }

    if (box.userId !== session.user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    // A box can only have one keyholder
    if (box.keyholder) {
      return NextResponse.json(
        { error: "This box already has a keyholder" },
        { status: 409 }
      );
    }

    // Create the keyholder — inviteToken is auto-generated by Prisma default
    const keyholder = await prisma.keyholder.create({
      data: {
        boxId,
        email: email.toLowerCase().trim(),
        name: name ?? null,
      },
    });

    // Send invite email to keyholder
    await sendKeyholderInvite({
      keyholderEmail: keyholder.email,
      keyholderName: keyholder.name,
      ownerName: session.user.name,
      boxName: box.name,
      inviteToken: keyholder.inviteToken,
    });

    // Return keyholder without the inviteToken
    const { inviteToken: _, ...safeKeyholder } = keyholder;

    return NextResponse.json(safeKeyholder, { status: 201 });
  } catch (error) {
    console.error("[POST /api/keyholders]", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
